#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 124
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 4

enum {
  sym__wordContent = 1,
  anon_sym_LF = 2,
  anon_sym_SEMI = 3,
  sym_Comment = 4,
  sym_EscapeSequence = 5,
  anon_sym_DQUOTE = 6,
  sym__quotedWordContent = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_DOLLAR = 10,
  sym_NumberExpression = 11,
  anon_sym_STAR_STAR = 12,
  anon_sym_STAR = 13,
  anon_sym_SLASH = 14,
  anon_sym_PLUS = 15,
  anon_sym_DASH = 16,
  anon_sym_LT = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_GT = 19,
  anon_sym_GT_EQ = 20,
  anon_sym_EQ_EQ = 21,
  anon_sym_BANG_EQ = 22,
  anon_sym_LPAREN = 23,
  anon_sym_RPAREN = 24,
  sym__concat = 25,
  sym_Program = 26,
  sym__statement = 27,
  sym_Command = 28,
  sym_WordList = 29,
  sym__word = 30,
  sym_Word = 31,
  sym_QuotedWord = 32,
  sym_ConcatenatedWord = 33,
  sym_Block = 34,
  sym_EvaluatedExpression = 35,
  sym_EvaluatedBlock = 36,
  sym_Expression = 37,
  sym__expression = 38,
  sym_VariableExpression = 39,
  sym__binaryExpression = 40,
  sym_ExponentExpression = 41,
  sym_MultiplicationExpression = 42,
  sym_DivisionExpression = 43,
  sym_AdditionExpression = 44,
  sym_SubtractionExpression = 45,
  sym__relationalExpression = 46,
  sym_LessThanExpression = 47,
  sym_LessThanOrEqualToExpression = 48,
  sym_GreaterThanExpression = 49,
  sym_GreaterThanOrEqualToExpression = 50,
  sym__equalityExpression = 51,
  sym_EqualToExpression = 52,
  sym_NotEqualToExpression = 53,
  sym_ParenthesizedExpression = 54,
  aux_sym_Program_repeat1 = 55,
  aux_sym_WordList_repeat1 = 56,
  aux_sym_Word_repeat1 = 57,
  aux_sym_QuotedWord_repeat1 = 58,
  aux_sym_ConcatenatedWord_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__wordContent] = "_wordContent",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_Comment] = "Comment",
  [sym_EscapeSequence] = "EscapeSequence",
  [anon_sym_DQUOTE] = "\"",
  [sym__quotedWordContent] = "_quotedWordContent",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOLLAR] = "$",
  [sym_NumberExpression] = "NumberExpression",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym__concat] = "_concat",
  [sym_Program] = "Program",
  [sym__statement] = "_statement",
  [sym_Command] = "Command",
  [sym_WordList] = "WordList",
  [sym__word] = "_word",
  [sym_Word] = "Word",
  [sym_QuotedWord] = "QuotedWord",
  [sym_ConcatenatedWord] = "ConcatenatedWord",
  [sym_Block] = "Block",
  [sym_EvaluatedExpression] = "EvaluatedExpression",
  [sym_EvaluatedBlock] = "EvaluatedBlock",
  [sym_Expression] = "Expression",
  [sym__expression] = "_expression",
  [sym_VariableExpression] = "VariableExpression",
  [sym__binaryExpression] = "_binaryExpression",
  [sym_ExponentExpression] = "ExponentExpression",
  [sym_MultiplicationExpression] = "MultiplicationExpression",
  [sym_DivisionExpression] = "DivisionExpression",
  [sym_AdditionExpression] = "AdditionExpression",
  [sym_SubtractionExpression] = "SubtractionExpression",
  [sym__relationalExpression] = "_relationalExpression",
  [sym_LessThanExpression] = "LessThanExpression",
  [sym_LessThanOrEqualToExpression] = "LessThanOrEqualToExpression",
  [sym_GreaterThanExpression] = "GreaterThanExpression",
  [sym_GreaterThanOrEqualToExpression] = "GreaterThanOrEqualToExpression",
  [sym__equalityExpression] = "_equalityExpression",
  [sym_EqualToExpression] = "EqualToExpression",
  [sym_NotEqualToExpression] = "NotEqualToExpression",
  [sym_ParenthesizedExpression] = "ParenthesizedExpression",
  [aux_sym_Program_repeat1] = "Program_repeat1",
  [aux_sym_WordList_repeat1] = "WordList_repeat1",
  [aux_sym_Word_repeat1] = "Word_repeat1",
  [aux_sym_QuotedWord_repeat1] = "QuotedWord_repeat1",
  [aux_sym_ConcatenatedWord_repeat1] = "ConcatenatedWord_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__wordContent] = sym__wordContent,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_Comment] = sym_Comment,
  [sym_EscapeSequence] = sym_EscapeSequence,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__quotedWordContent] = sym__quotedWordContent,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_NumberExpression] = sym_NumberExpression,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym__concat] = sym__concat,
  [sym_Program] = sym_Program,
  [sym__statement] = sym__statement,
  [sym_Command] = sym_Command,
  [sym_WordList] = sym_WordList,
  [sym__word] = sym__word,
  [sym_Word] = sym_Word,
  [sym_QuotedWord] = sym_QuotedWord,
  [sym_ConcatenatedWord] = sym_ConcatenatedWord,
  [sym_Block] = sym_Block,
  [sym_EvaluatedExpression] = sym_EvaluatedExpression,
  [sym_EvaluatedBlock] = sym_EvaluatedBlock,
  [sym_Expression] = sym_Expression,
  [sym__expression] = sym__expression,
  [sym_VariableExpression] = sym_VariableExpression,
  [sym__binaryExpression] = sym__binaryExpression,
  [sym_ExponentExpression] = sym_ExponentExpression,
  [sym_MultiplicationExpression] = sym_MultiplicationExpression,
  [sym_DivisionExpression] = sym_DivisionExpression,
  [sym_AdditionExpression] = sym_AdditionExpression,
  [sym_SubtractionExpression] = sym_SubtractionExpression,
  [sym__relationalExpression] = sym__relationalExpression,
  [sym_LessThanExpression] = sym_LessThanExpression,
  [sym_LessThanOrEqualToExpression] = sym_LessThanOrEqualToExpression,
  [sym_GreaterThanExpression] = sym_GreaterThanExpression,
  [sym_GreaterThanOrEqualToExpression] = sym_GreaterThanOrEqualToExpression,
  [sym__equalityExpression] = sym__equalityExpression,
  [sym_EqualToExpression] = sym_EqualToExpression,
  [sym_NotEqualToExpression] = sym_NotEqualToExpression,
  [sym_ParenthesizedExpression] = sym_ParenthesizedExpression,
  [aux_sym_Program_repeat1] = aux_sym_Program_repeat1,
  [aux_sym_WordList_repeat1] = aux_sym_WordList_repeat1,
  [aux_sym_Word_repeat1] = aux_sym_Word_repeat1,
  [aux_sym_QuotedWord_repeat1] = aux_sym_QuotedWord_repeat1,
  [aux_sym_ConcatenatedWord_repeat1] = aux_sym_ConcatenatedWord_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__wordContent] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_Comment] = {
    .visible = true,
    .named = true,
  },
  [sym_EscapeSequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__quotedWordContent] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_NumberExpression] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym__concat] = {
    .visible = false,
    .named = true,
  },
  [sym_Program] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_Command] = {
    .visible = true,
    .named = true,
  },
  [sym_WordList] = {
    .visible = true,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_Word] = {
    .visible = true,
    .named = true,
  },
  [sym_QuotedWord] = {
    .visible = true,
    .named = true,
  },
  [sym_ConcatenatedWord] = {
    .visible = true,
    .named = true,
  },
  [sym_Block] = {
    .visible = true,
    .named = true,
  },
  [sym_EvaluatedExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_EvaluatedBlock] = {
    .visible = true,
    .named = true,
  },
  [sym_Expression] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_VariableExpression] = {
    .visible = true,
    .named = true,
  },
  [sym__binaryExpression] = {
    .visible = false,
    .named = true,
  },
  [sym_ExponentExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_MultiplicationExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_DivisionExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_AdditionExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_SubtractionExpression] = {
    .visible = true,
    .named = true,
  },
  [sym__relationalExpression] = {
    .visible = false,
    .named = true,
  },
  [sym_LessThanExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_LessThanOrEqualToExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_GreaterThanExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_GreaterThanOrEqualToExpression] = {
    .visible = true,
    .named = true,
  },
  [sym__equalityExpression] = {
    .visible = false,
    .named = true,
  },
  [sym_EqualToExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_NotEqualToExpression] = {
    .visible = true,
    .named = true,
  },
  [sym_ParenthesizedExpression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_Program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_WordList_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_Word_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_QuotedWord_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ConcatenatedWord_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_left = 2,
  field_name = 3,
  field_right = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_left] = "left",
  [field_name] = "name",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_arguments, 1},
    {field_name, 0},
  [3] =
    {field_left, 0},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static inline bool sym_Comment_character_set_1(int32_t c) {
  return (c < '('
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= ' ' || (c < '$'
        ? c == '"'
        : c <= '$')))
    : (c <= ')' || (c < '{'
      ? (c < '\\'
        ? c == ';'
        : c <= '\\')
      : (c <= '{' || c == '}'))));
}

static inline bool sym__wordContent_character_set_1(int32_t c) {
  return (c < '$'
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '"'
        ? c == ' '
        : c <= '"')))
    : (c <= '$' || (c < '\\'
      ? (c < ';'
        ? (c >= '(' && c <= ')')
        : c <= ';')
      : (c <= '\\' || (c < '}'
        ? c == '{'
        : c <= '}')))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '!') ADVANCE(14);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '=') ADVANCE(15);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\r') ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '=') ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3)
      if (lookahead == '!') ADVANCE(1);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead == '+') ADVANCE(32);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '=') ADVANCE(2);
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6)
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != ')') ADVANCE(18);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7)
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != ')') ADVANCE(18);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_Comment);
      if (sym_Comment_character_set_1(lookahead)) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_Comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__wordContent);
      if (lookahead == '.') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__wordContent);
      if (lookahead == '=') ADVANCE(47);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__wordContent);
      if (lookahead == '=') ADVANCE(45);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__wordContent);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__wordContent);
      if (sym_Comment_character_set_1(lookahead)) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__wordContent);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_EscapeSequence);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__quotedWordContent);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__quotedWordContent);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(27);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(26);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(39);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(43);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      if (!sym__wordContent_character_set_1(lookahead)) ADVANCE(18);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 6, .external_lex_state = 2},
  [20] = {.lex_state = 6, .external_lex_state = 2},
  [21] = {.lex_state = 6, .external_lex_state = 2},
  [22] = {.lex_state = 6, .external_lex_state = 2},
  [23] = {.lex_state = 6, .external_lex_state = 2},
  [24] = {.lex_state = 6, .external_lex_state = 2},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6, .external_lex_state = 2},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7, .external_lex_state = 2},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7, .external_lex_state = 2},
  [32] = {.lex_state = 7, .external_lex_state = 2},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 3, .external_lex_state = 3},
  [35] = {.lex_state = 3, .external_lex_state = 3},
  [36] = {.lex_state = 3, .external_lex_state = 3},
  [37] = {.lex_state = 3, .external_lex_state = 3},
  [38] = {.lex_state = 3, .external_lex_state = 4},
  [39] = {.lex_state = 3, .external_lex_state = 4},
  [40] = {.lex_state = 3, .external_lex_state = 4},
  [41] = {.lex_state = 3, .external_lex_state = 4},
  [42] = {.lex_state = 3, .external_lex_state = 4},
  [43] = {.lex_state = 3, .external_lex_state = 4},
  [44] = {.lex_state = 3, .external_lex_state = 4},
  [45] = {.lex_state = 3, .external_lex_state = 4},
  [46] = {.lex_state = 3, .external_lex_state = 4},
  [47] = {.lex_state = 3, .external_lex_state = 4},
  [48] = {.lex_state = 3, .external_lex_state = 4},
  [49] = {.lex_state = 3, .external_lex_state = 4},
  [50] = {.lex_state = 3, .external_lex_state = 4},
  [51] = {.lex_state = 3, .external_lex_state = 4},
  [52] = {.lex_state = 7, .external_lex_state = 5},
  [53] = {.lex_state = 7, .external_lex_state = 6},
  [54] = {.lex_state = 7, .external_lex_state = 5},
  [55] = {.lex_state = 7, .external_lex_state = 5},
  [56] = {.lex_state = 7, .external_lex_state = 5},
  [57] = {.lex_state = 7, .external_lex_state = 6},
  [58] = {.lex_state = 7, .external_lex_state = 5},
  [59] = {.lex_state = 7, .external_lex_state = 6},
  [60] = {.lex_state = 7, .external_lex_state = 6},
  [61] = {.lex_state = 7, .external_lex_state = 6},
  [62] = {.lex_state = 7, .external_lex_state = 6},
  [63] = {.lex_state = 7, .external_lex_state = 5},
  [64] = {.lex_state = 7, .external_lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 7, .external_lex_state = 5},
  [67] = {.lex_state = 7, .external_lex_state = 5},
  [68] = {.lex_state = 7, .external_lex_state = 6},
  [69] = {.lex_state = 7, .external_lex_state = 5},
  [70] = {.lex_state = 7, .external_lex_state = 6},
  [71] = {.lex_state = 6, .external_lex_state = 2},
  [72] = {.lex_state = 7, .external_lex_state = 2},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 7, .external_lex_state = 2},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 7, .external_lex_state = 2},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 7, .external_lex_state = 2},
  [80] = {.lex_state = 7, .external_lex_state = 2},
  [81] = {.lex_state = 7},
  [82] = {.lex_state = 7},
  [83] = {.lex_state = 7, .external_lex_state = 2},
  [84] = {.lex_state = 7, .external_lex_state = 2},
  [85] = {.lex_state = 7},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 4},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 7},
  [92] = {.lex_state = 7},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 4},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 4},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 4},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 7},
  [114] = {.lex_state = 7},
  [115] = {.lex_state = 7},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0, .external_lex_state = 4},
  [118] = {.lex_state = 0, .external_lex_state = 4},
  [119] = {.lex_state = 0, .external_lex_state = 4},
  [120] = {.lex_state = 0, .external_lex_state = 4},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0, .external_lex_state = 4},
  [123] = {.lex_state = 0, .external_lex_state = 4},
};

enum {
  ts_external_token__concat = 0,
  ts_external_token_RBRACE = 1,
  ts_external_token_RPAREN = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__concat] = sym__concat,
  [ts_external_token_RBRACE] = anon_sym_RBRACE,
  [ts_external_token_RPAREN] = anon_sym_RPAREN,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__concat] = true,
    [ts_external_token_RBRACE] = true,
    [ts_external_token_RPAREN] = true,
  },
  [2] = {
    [ts_external_token_RBRACE] = true,
  },
  [3] = {
    [ts_external_token__concat] = true,
    [ts_external_token_RPAREN] = true,
  },
  [4] = {
    [ts_external_token_RPAREN] = true,
  },
  [5] = {
    [ts_external_token__concat] = true,
  },
  [6] = {
    [ts_external_token__concat] = true,
    [ts_external_token_RBRACE] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__wordContent] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_Comment] = ACTIONS(1),
    [sym_EscapeSequence] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym__concat] = ACTIONS(1),
  },
  [1] = {
    [sym_Program] = STATE(121),
    [sym__statement] = STATE(104),
    [sym_Command] = STATE(104),
    [sym__word] = STATE(28),
    [sym_Word] = STATE(63),
    [sym_QuotedWord] = STATE(28),
    [sym_ConcatenatedWord] = STATE(28),
    [sym_Block] = STATE(28),
    [sym_EvaluatedExpression] = STATE(28),
    [sym_EvaluatedBlock] = STATE(28),
    [sym_ParenthesizedExpression] = STATE(63),
    [aux_sym_Program_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__wordContent] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [sym_Comment] = ACTIONS(9),
    [sym_EscapeSequence] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(23), 1,
      sym_NumberExpression,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_Word,
    STATE(120), 1,
      sym_Expression,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(40), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [36] = 6,
    ACTIONS(23), 1,
      sym_NumberExpression,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_Word,
    STATE(119), 1,
      sym_Expression,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(40), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [72] = 6,
    ACTIONS(23), 1,
      sym_NumberExpression,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_Word,
    STATE(118), 1,
      sym_Expression,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(40), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [108] = 6,
    ACTIONS(23), 1,
      sym_NumberExpression,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_Word,
    STATE(117), 1,
      sym_Expression,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(40), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [144] = 6,
    ACTIONS(23), 1,
      sym_NumberExpression,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_Word,
    STATE(123), 1,
      sym_Expression,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(40), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [180] = 6,
    ACTIONS(23), 1,
      sym_NumberExpression,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(46), 1,
      sym_Word,
    STATE(122), 1,
      sym_Expression,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(40), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [216] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(41), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [249] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(47), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [282] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(50), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [315] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(48), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [348] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(49), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [381] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(43), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [414] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(42), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [447] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(44), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [480] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(51), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [513] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(45), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(39), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [546] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym_NumberExpression,
    STATE(46), 1,
      sym_Word,
    ACTIONS(21), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(38), 17,
      sym__expression,
      sym_VariableExpression,
      sym__binaryExpression,
      sym_ExponentExpression,
      sym_MultiplicationExpression,
      sym_DivisionExpression,
      sym_AdditionExpression,
      sym_SubtractionExpression,
      sym__relationalExpression,
      sym_LessThanExpression,
      sym_LessThanOrEqualToExpression,
      sym_GreaterThanExpression,
      sym_GreaterThanOrEqualToExpression,
      sym__equalityExpression,
      sym_EqualToExpression,
      sym_NotEqualToExpression,
      sym_ParenthesizedExpression,
  [579] = 13,
    ACTIONS(49), 1,
      sym__wordContent,
    ACTIONS(53), 1,
      sym_Comment,
    ACTIONS(55), 1,
      sym_EscapeSequence,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      aux_sym_Program_repeat1,
    ACTIONS(51), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(102), 2,
      sym__statement,
      sym_Command,
    STATE(29), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [627] = 13,
    ACTIONS(49), 1,
      sym__wordContent,
    ACTIONS(55), 1,
      sym_EscapeSequence,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_Comment,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_Program_repeat1,
    ACTIONS(67), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(103), 2,
      sym__statement,
      sym_Command,
    STATE(29), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [675] = 13,
    ACTIONS(73), 1,
      sym__wordContent,
    ACTIONS(79), 1,
      sym_Comment,
    ACTIONS(82), 1,
      sym_EscapeSequence,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    ACTIONS(93), 1,
      anon_sym_DOLLAR,
    ACTIONS(96), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      aux_sym_Program_repeat1,
    ACTIONS(76), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(63), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(116), 2,
      sym__statement,
      sym_Command,
    STATE(28), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [723] = 13,
    ACTIONS(49), 1,
      sym__wordContent,
    ACTIONS(55), 1,
      sym_EscapeSequence,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(101), 1,
      sym_Comment,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym_Program_repeat1,
    ACTIONS(99), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(105), 2,
      sym__statement,
      sym_Command,
    STATE(29), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [771] = 13,
    ACTIONS(49), 1,
      sym__wordContent,
    ACTIONS(55), 1,
      sym_EscapeSequence,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      sym_Comment,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_Program_repeat1,
    ACTIONS(67), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(106), 2,
      sym__statement,
      sym_Command,
    STATE(29), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [819] = 13,
    ACTIONS(49), 1,
      sym__wordContent,
    ACTIONS(55), 1,
      sym_EscapeSequence,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      sym_Comment,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym_Program_repeat1,
    ACTIONS(109), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(108), 2,
      sym__statement,
      sym_Command,
    STATE(29), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [867] = 13,
    ACTIONS(73), 1,
      sym__wordContent,
    ACTIONS(82), 1,
      sym_EscapeSequence,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      anon_sym_DOLLAR,
    ACTIONS(96), 1,
      anon_sym_LPAREN,
    ACTIONS(118), 1,
      sym_Comment,
    STATE(25), 1,
      aux_sym_Program_repeat1,
    ACTIONS(115), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(63), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(112), 2,
      sym__statement,
      sym_Command,
    STATE(28), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [915] = 13,
    ACTIONS(5), 1,
      sym__wordContent,
    ACTIONS(11), 1,
      sym_EscapeSequence,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_DOLLAR,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 1,
      sym_Comment,
    STATE(25), 1,
      aux_sym_Program_repeat1,
    ACTIONS(123), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(63), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(111), 2,
      sym__statement,
      sym_Command,
    STATE(28), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [963] = 13,
    ACTIONS(49), 1,
      sym__wordContent,
    ACTIONS(55), 1,
      sym_EscapeSequence,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      sym_Comment,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_Program_repeat1,
    ACTIONS(67), 2,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    STATE(109), 2,
      sym__statement,
      sym_Command,
    STATE(29), 6,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
  [1011] = 9,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_DOLLAR,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(107), 1,
      sym_WordList,
    ACTIONS(11), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(63), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(30), 7,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_WordList_repeat1,
  [1049] = 9,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    STATE(110), 1,
      sym_WordList,
    ACTIONS(55), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    ACTIONS(131), 3,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(31), 7,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_WordList_repeat1,
  [1087] = 8,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_DOLLAR,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(63), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(33), 7,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_WordList_repeat1,
  [1122] = 8,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    ACTIONS(133), 3,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(32), 7,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_WordList_repeat1,
  [1157] = 8,
    ACTIONS(140), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
    ACTIONS(146), 1,
      anon_sym_DOLLAR,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(59), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    ACTIONS(138), 3,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(32), 7,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_WordList_repeat1,
  [1192] = 8,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(158), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      anon_sym_DOLLAR,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(63), 2,
      sym_Word,
      sym_ParenthesizedExpression,
    ACTIONS(138), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
    STATE(33), 7,
      sym__word,
      sym_QuotedWord,
      sym_ConcatenatedWord,
      sym_Block,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_WordList_repeat1,
  [1227] = 4,
    ACTIONS(171), 1,
      sym__concat,
    STATE(34), 1,
      aux_sym_Word_repeat1,
    ACTIONS(169), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(167), 9,
      anon_sym_STAR_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1250] = 4,
    ACTIONS(178), 1,
      sym__concat,
    STATE(36), 1,
      aux_sym_Word_repeat1,
    ACTIONS(176), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 9,
      anon_sym_STAR_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1273] = 4,
    ACTIONS(178), 1,
      sym__concat,
    STATE(34), 1,
      aux_sym_Word_repeat1,
    ACTIONS(182), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(180), 9,
      anon_sym_STAR_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1296] = 2,
    ACTIONS(186), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(184), 10,
      sym__concat,
      anon_sym_STAR_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1314] = 10,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(194), 1,
      anon_sym_PLUS,
    ACTIONS(196), 1,
      anon_sym_DASH,
    ACTIONS(198), 1,
      anon_sym_LT,
    ACTIONS(200), 1,
      anon_sym_LT_EQ,
    ACTIONS(202), 1,
      anon_sym_GT,
    ACTIONS(204), 1,
      anon_sym_GT_EQ,
    ACTIONS(206), 3,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1347] = 10,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(194), 1,
      anon_sym_PLUS,
    ACTIONS(196), 1,
      anon_sym_DASH,
    ACTIONS(198), 1,
      anon_sym_LT,
    ACTIONS(200), 1,
      anon_sym_LT_EQ,
    ACTIONS(202), 1,
      anon_sym_GT,
    ACTIONS(204), 1,
      anon_sym_GT_EQ,
    ACTIONS(208), 3,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1380] = 12,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(194), 1,
      anon_sym_PLUS,
    ACTIONS(196), 1,
      anon_sym_DASH,
    ACTIONS(198), 1,
      anon_sym_LT,
    ACTIONS(200), 1,
      anon_sym_LT_EQ,
    ACTIONS(202), 1,
      anon_sym_GT,
    ACTIONS(204), 1,
      anon_sym_GT_EQ,
    ACTIONS(210), 1,
      anon_sym_EQ_EQ,
    ACTIONS(212), 1,
      anon_sym_BANG_EQ,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
  [1417] = 7,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(194), 1,
      anon_sym_PLUS,
    ACTIONS(196), 1,
      anon_sym_DASH,
    ACTIONS(216), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(218), 5,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1444] = 7,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(194), 1,
      anon_sym_PLUS,
    ACTIONS(196), 1,
      anon_sym_DASH,
    ACTIONS(220), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(222), 5,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1471] = 7,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(194), 1,
      anon_sym_PLUS,
    ACTIONS(196), 1,
      anon_sym_DASH,
    ACTIONS(224), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(226), 5,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1498] = 7,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(194), 1,
      anon_sym_PLUS,
    ACTIONS(196), 1,
      anon_sym_DASH,
    ACTIONS(228), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(230), 5,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1525] = 2,
    ACTIONS(234), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(232), 9,
      anon_sym_STAR_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1542] = 2,
    ACTIONS(238), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(236), 9,
      anon_sym_STAR_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1559] = 5,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(242), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(240), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1582] = 5,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(190), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_SLASH,
    ACTIONS(246), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(244), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1605] = 3,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(248), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(250), 8,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1624] = 3,
    ACTIONS(188), 1,
      anon_sym_STAR_STAR,
    ACTIONS(252), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(254), 8,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1643] = 2,
    ACTIONS(258), 3,
      anon_sym_STAR,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(256), 9,
      anon_sym_STAR_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
  [1660] = 3,
    ACTIONS(262), 1,
      sym__concat,
    STATE(52), 1,
      aux_sym_ConcatenatedWord_repeat1,
    ACTIONS(260), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1678] = 3,
    ACTIONS(265), 1,
      sym__concat,
    STATE(53), 1,
      aux_sym_ConcatenatedWord_repeat1,
    ACTIONS(260), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1696] = 3,
    ACTIONS(268), 1,
      sym__concat,
    STATE(54), 1,
      aux_sym_Word_repeat1,
    ACTIONS(167), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1714] = 3,
    ACTIONS(271), 1,
      sym__concat,
    STATE(54), 1,
      aux_sym_Word_repeat1,
    ACTIONS(180), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1732] = 3,
    ACTIONS(276), 1,
      sym__concat,
    STATE(52), 1,
      aux_sym_ConcatenatedWord_repeat1,
    ACTIONS(274), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1750] = 3,
    ACTIONS(278), 1,
      sym__concat,
    STATE(60), 1,
      aux_sym_Word_repeat1,
    ACTIONS(174), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1768] = 3,
    ACTIONS(281), 1,
      sym__concat,
    STATE(55), 1,
      aux_sym_Word_repeat1,
    ACTIONS(174), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1786] = 3,
    ACTIONS(286), 1,
      sym__concat,
    STATE(62), 1,
      aux_sym_ConcatenatedWord_repeat1,
    ACTIONS(284), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1804] = 3,
    ACTIONS(288), 1,
      sym__concat,
    STATE(61), 1,
      aux_sym_Word_repeat1,
    ACTIONS(180), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1822] = 3,
    ACTIONS(291), 1,
      sym__concat,
    STATE(61), 1,
      aux_sym_Word_repeat1,
    ACTIONS(167), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1840] = 3,
    ACTIONS(286), 1,
      sym__concat,
    STATE(53), 1,
      aux_sym_ConcatenatedWord_repeat1,
    ACTIONS(274), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1858] = 3,
    ACTIONS(276), 1,
      sym__concat,
    STATE(56), 1,
      aux_sym_ConcatenatedWord_repeat1,
    ACTIONS(284), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1876] = 1,
    ACTIONS(232), 10,
      sym__concat,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1889] = 2,
    ACTIONS(294), 1,
      sym__wordContent,
    ACTIONS(91), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym_Comment,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1904] = 1,
    ACTIONS(260), 10,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1917] = 1,
    ACTIONS(232), 10,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1930] = 1,
    ACTIONS(260), 10,
      sym__concat,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1943] = 1,
    ACTIONS(184), 10,
      sym__concat,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1956] = 1,
    ACTIONS(184), 10,
      sym__concat,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1969] = 2,
    ACTIONS(294), 1,
      sym__wordContent,
    ACTIONS(91), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym_Comment,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1984] = 1,
    ACTIONS(296), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [1996] = 1,
    ACTIONS(232), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2008] = 1,
    ACTIONS(298), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2020] = 1,
    ACTIONS(300), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2032] = 1,
    ACTIONS(302), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2044] = 1,
    ACTIONS(302), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2056] = 1,
    ACTIONS(298), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2068] = 1,
    ACTIONS(232), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2080] = 1,
    ACTIONS(300), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2092] = 1,
    ACTIONS(296), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2104] = 1,
    ACTIONS(304), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2116] = 1,
    ACTIONS(306), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2128] = 1,
    ACTIONS(304), 9,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2140] = 1,
    ACTIONS(306), 9,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
      sym__wordContent,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_LPAREN,
  [2152] = 5,
    ACTIONS(308), 1,
      sym_EscapeSequence,
    ACTIONS(310), 1,
      anon_sym_DQUOTE,
    ACTIONS(312), 1,
      sym__quotedWordContent,
    ACTIONS(314), 1,
      anon_sym_DOLLAR,
    STATE(88), 3,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_QuotedWord_repeat1,
  [2170] = 5,
    ACTIONS(308), 1,
      sym_EscapeSequence,
    ACTIONS(312), 1,
      sym__quotedWordContent,
    ACTIONS(314), 1,
      anon_sym_DOLLAR,
    ACTIONS(316), 1,
      anon_sym_DQUOTE,
    STATE(88), 3,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_QuotedWord_repeat1,
  [2188] = 5,
    ACTIONS(318), 1,
      sym_EscapeSequence,
    ACTIONS(321), 1,
      anon_sym_DQUOTE,
    ACTIONS(323), 1,
      sym__quotedWordContent,
    ACTIONS(326), 1,
      anon_sym_DOLLAR,
    STATE(88), 3,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_QuotedWord_repeat1,
  [2206] = 4,
    ACTIONS(314), 1,
      anon_sym_DOLLAR,
    ACTIONS(329), 1,
      sym_EscapeSequence,
    ACTIONS(331), 1,
      sym__quotedWordContent,
    STATE(86), 3,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_QuotedWord_repeat1,
  [2221] = 4,
    ACTIONS(314), 1,
      anon_sym_DOLLAR,
    ACTIONS(333), 1,
      sym_EscapeSequence,
    ACTIONS(335), 1,
      sym__quotedWordContent,
    STATE(87), 3,
      sym_EvaluatedExpression,
      sym_EvaluatedBlock,
      aux_sym_QuotedWord_repeat1,
  [2236] = 3,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(68), 2,
      sym_Word,
      sym_ParenthesizedExpression,
  [2248] = 3,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 2,
      sym__wordContent,
      sym_EscapeSequence,
    STATE(66), 2,
      sym_Word,
      sym_ParenthesizedExpression,
  [2260] = 4,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(337), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_Block,
    STATE(84), 1,
      sym_ParenthesizedExpression,
  [2273] = 2,
    ACTIONS(304), 1,
      sym__quotedWordContent,
    ACTIONS(339), 3,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
  [2282] = 4,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(341), 1,
      anon_sym_LPAREN,
    STATE(82), 1,
      sym_ParenthesizedExpression,
    STATE(85), 1,
      sym_Block,
  [2295] = 2,
    ACTIONS(296), 1,
      sym__quotedWordContent,
    ACTIONS(343), 3,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
  [2304] = 2,
    ACTIONS(300), 1,
      sym__quotedWordContent,
    ACTIONS(345), 3,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
  [2313] = 2,
    ACTIONS(232), 1,
      sym__quotedWordContent,
    ACTIONS(234), 3,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
  [2322] = 2,
    ACTIONS(306), 1,
      sym__quotedWordContent,
    ACTIONS(347), 3,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
  [2331] = 2,
    ACTIONS(298), 1,
      sym__quotedWordContent,
    ACTIONS(349), 3,
      sym_EscapeSequence,
      anon_sym_DQUOTE,
      anon_sym_DOLLAR,
  [2340] = 4,
    ACTIONS(351), 1,
      anon_sym_LBRACE,
    ACTIONS(353), 1,
      anon_sym_LPAREN,
    STATE(94), 1,
      sym_ParenthesizedExpression,
    STATE(99), 1,
      sym_Block,
  [2353] = 2,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(355), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2361] = 2,
    ACTIONS(357), 1,
      anon_sym_RBRACE,
    ACTIONS(355), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2369] = 2,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(359), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2377] = 2,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(355), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2385] = 2,
    ACTIONS(361), 1,
      anon_sym_RBRACE,
    ACTIONS(355), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2393] = 1,
    ACTIONS(363), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_SEMI,
  [2399] = 2,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(355), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2407] = 2,
    ACTIONS(365), 1,
      anon_sym_RBRACE,
    ACTIONS(355), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2415] = 1,
    ACTIONS(363), 3,
      anon_sym_LF,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2421] = 2,
    ACTIONS(367), 1,
      ts_builtin_sym_end,
    ACTIONS(359), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2429] = 1,
    ACTIONS(359), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2434] = 1,
    ACTIONS(369), 2,
      sym__wordContent,
      sym_EscapeSequence,
  [2439] = 1,
    ACTIONS(371), 2,
      sym__wordContent,
      sym_EscapeSequence,
  [2444] = 1,
    ACTIONS(373), 2,
      sym__wordContent,
      sym_EscapeSequence,
  [2449] = 1,
    ACTIONS(355), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [2454] = 1,
    ACTIONS(375), 1,
      anon_sym_RPAREN,
  [2458] = 1,
    ACTIONS(377), 1,
      anon_sym_RPAREN,
  [2462] = 1,
    ACTIONS(379), 1,
      anon_sym_RPAREN,
  [2466] = 1,
    ACTIONS(381), 1,
      anon_sym_RPAREN,
  [2470] = 1,
    ACTIONS(383), 1,
      ts_builtin_sym_end,
  [2474] = 1,
    ACTIONS(385), 1,
      anon_sym_RPAREN,
  [2478] = 1,
    ACTIONS(387), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 249,
  [SMALL_STATE(10)] = 282,
  [SMALL_STATE(11)] = 315,
  [SMALL_STATE(12)] = 348,
  [SMALL_STATE(13)] = 381,
  [SMALL_STATE(14)] = 414,
  [SMALL_STATE(15)] = 447,
  [SMALL_STATE(16)] = 480,
  [SMALL_STATE(17)] = 513,
  [SMALL_STATE(18)] = 546,
  [SMALL_STATE(19)] = 579,
  [SMALL_STATE(20)] = 627,
  [SMALL_STATE(21)] = 675,
  [SMALL_STATE(22)] = 723,
  [SMALL_STATE(23)] = 771,
  [SMALL_STATE(24)] = 819,
  [SMALL_STATE(25)] = 867,
  [SMALL_STATE(26)] = 915,
  [SMALL_STATE(27)] = 963,
  [SMALL_STATE(28)] = 1011,
  [SMALL_STATE(29)] = 1049,
  [SMALL_STATE(30)] = 1087,
  [SMALL_STATE(31)] = 1122,
  [SMALL_STATE(32)] = 1157,
  [SMALL_STATE(33)] = 1192,
  [SMALL_STATE(34)] = 1227,
  [SMALL_STATE(35)] = 1250,
  [SMALL_STATE(36)] = 1273,
  [SMALL_STATE(37)] = 1296,
  [SMALL_STATE(38)] = 1314,
  [SMALL_STATE(39)] = 1347,
  [SMALL_STATE(40)] = 1380,
  [SMALL_STATE(41)] = 1417,
  [SMALL_STATE(42)] = 1444,
  [SMALL_STATE(43)] = 1471,
  [SMALL_STATE(44)] = 1498,
  [SMALL_STATE(45)] = 1525,
  [SMALL_STATE(46)] = 1542,
  [SMALL_STATE(47)] = 1559,
  [SMALL_STATE(48)] = 1582,
  [SMALL_STATE(49)] = 1605,
  [SMALL_STATE(50)] = 1624,
  [SMALL_STATE(51)] = 1643,
  [SMALL_STATE(52)] = 1660,
  [SMALL_STATE(53)] = 1678,
  [SMALL_STATE(54)] = 1696,
  [SMALL_STATE(55)] = 1714,
  [SMALL_STATE(56)] = 1732,
  [SMALL_STATE(57)] = 1750,
  [SMALL_STATE(58)] = 1768,
  [SMALL_STATE(59)] = 1786,
  [SMALL_STATE(60)] = 1804,
  [SMALL_STATE(61)] = 1822,
  [SMALL_STATE(62)] = 1840,
  [SMALL_STATE(63)] = 1858,
  [SMALL_STATE(64)] = 1876,
  [SMALL_STATE(65)] = 1889,
  [SMALL_STATE(66)] = 1904,
  [SMALL_STATE(67)] = 1917,
  [SMALL_STATE(68)] = 1930,
  [SMALL_STATE(69)] = 1943,
  [SMALL_STATE(70)] = 1956,
  [SMALL_STATE(71)] = 1969,
  [SMALL_STATE(72)] = 1984,
  [SMALL_STATE(73)] = 1996,
  [SMALL_STATE(74)] = 2008,
  [SMALL_STATE(75)] = 2020,
  [SMALL_STATE(76)] = 2032,
  [SMALL_STATE(77)] = 2044,
  [SMALL_STATE(78)] = 2056,
  [SMALL_STATE(79)] = 2068,
  [SMALL_STATE(80)] = 2080,
  [SMALL_STATE(81)] = 2092,
  [SMALL_STATE(82)] = 2104,
  [SMALL_STATE(83)] = 2116,
  [SMALL_STATE(84)] = 2128,
  [SMALL_STATE(85)] = 2140,
  [SMALL_STATE(86)] = 2152,
  [SMALL_STATE(87)] = 2170,
  [SMALL_STATE(88)] = 2188,
  [SMALL_STATE(89)] = 2206,
  [SMALL_STATE(90)] = 2221,
  [SMALL_STATE(91)] = 2236,
  [SMALL_STATE(92)] = 2248,
  [SMALL_STATE(93)] = 2260,
  [SMALL_STATE(94)] = 2273,
  [SMALL_STATE(95)] = 2282,
  [SMALL_STATE(96)] = 2295,
  [SMALL_STATE(97)] = 2304,
  [SMALL_STATE(98)] = 2313,
  [SMALL_STATE(99)] = 2322,
  [SMALL_STATE(100)] = 2331,
  [SMALL_STATE(101)] = 2340,
  [SMALL_STATE(102)] = 2353,
  [SMALL_STATE(103)] = 2361,
  [SMALL_STATE(104)] = 2369,
  [SMALL_STATE(105)] = 2377,
  [SMALL_STATE(106)] = 2385,
  [SMALL_STATE(107)] = 2393,
  [SMALL_STATE(108)] = 2399,
  [SMALL_STATE(109)] = 2407,
  [SMALL_STATE(110)] = 2415,
  [SMALL_STATE(111)] = 2421,
  [SMALL_STATE(112)] = 2429,
  [SMALL_STATE(113)] = 2434,
  [SMALL_STATE(114)] = 2439,
  [SMALL_STATE(115)] = 2444,
  [SMALL_STATE(116)] = 2449,
  [SMALL_STATE(117)] = 2454,
  [SMALL_STATE(118)] = 2458,
  [SMALL_STATE(119)] = 2462,
  [SMALL_STATE(120)] = 2466,
  [SMALL_STATE(121)] = 2470,
  [SMALL_STATE(122)] = 2474,
  [SMALL_STATE(123)] = 2478,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Program, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(58),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(21),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(116),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(58),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(89),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(22),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(95),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(5),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(25),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Program_repeat1, 2), SHIFT_REPEAT(112),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Program, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Command, 1, .production_id = 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_WordList, 1),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(57),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(90),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(19),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(93),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(7),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(58),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(89),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(22),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(95),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_WordList_repeat1, 2), SHIFT_REPEAT(5),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Word_repeat1, 2),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_Word_repeat1, 2),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Word_repeat1, 2), SHIFT_REPEAT(114),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Word, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Word, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Word, 2),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Word, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Word_repeat1, 2, .dynamic_precedence = 1),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_Word_repeat1, 2, .dynamic_precedence = 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_EqualToExpression, 3, .production_id = 3),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_NotEqualToExpression, 3, .production_id = 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Expression, 1),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_GreaterThanOrEqualToExpression, 3, .production_id = 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_GreaterThanOrEqualToExpression, 3, .production_id = 3),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_GreaterThanExpression, 3, .production_id = 3),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_GreaterThanExpression, 3, .production_id = 3),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_LessThanOrEqualToExpression, 3, .production_id = 3),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_LessThanOrEqualToExpression, 3, .production_id = 3),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_LessThanExpression, 3, .production_id = 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_LessThanExpression, 3, .production_id = 3),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ParenthesizedExpression, 3),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ParenthesizedExpression, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_VariableExpression, 1),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_VariableExpression, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_SubtractionExpression, 3, .production_id = 3),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_SubtractionExpression, 3, .production_id = 3),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_AdditionExpression, 3, .production_id = 3),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_AdditionExpression, 3, .production_id = 3),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_DivisionExpression, 3, .production_id = 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_DivisionExpression, 3, .production_id = 3),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_MultiplicationExpression, 3, .production_id = 3),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_MultiplicationExpression, 3, .production_id = 3),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ExponentExpression, 3, .production_id = 3),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ExponentExpression, 3, .production_id = 3),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ConcatenatedWord_repeat1, 2),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ConcatenatedWord_repeat1, 2), SHIFT_REPEAT(92),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ConcatenatedWord_repeat1, 2), SHIFT_REPEAT(91),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Word_repeat1, 2), SHIFT_REPEAT(115),
  [271] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_Word, 2), SHIFT(115),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ConcatenatedWord, 2),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_Word, 1), SHIFT(113),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_Word, 1), SHIFT(115),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__word, 1),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [288] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_Word, 2), SHIFT(113),
  [291] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_Word_repeat1, 2), SHIFT_REPEAT(113),
  [294] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_Program_repeat1, 2),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Block, 3),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Block, 2),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Block, 4),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_QuotedWord, 3),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_EvaluatedExpression, 2),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_EvaluatedBlock, 2),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [310] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [314] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [318] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_QuotedWord_repeat1, 2), SHIFT_REPEAT(88),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_QuotedWord_repeat1, 2),
  [323] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_QuotedWord_repeat1, 2), SHIFT_REPEAT(88),
  [326] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_QuotedWord_repeat1, 2), SHIFT_REPEAT(101),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [333] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [339] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_EvaluatedExpression, 2),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [343] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Block, 3),
  [345] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Block, 4),
  [347] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_EvaluatedBlock, 2),
  [349] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Block, 2),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Command, 2, .production_id = 2),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Program, 2),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [383] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_fugu_external_scanner_create(void);
void tree_sitter_fugu_external_scanner_destroy(void *);
bool tree_sitter_fugu_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_fugu_external_scanner_serialize(void *, char *);
void tree_sitter_fugu_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_fugu(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__wordContent,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_fugu_external_scanner_create,
      tree_sitter_fugu_external_scanner_destroy,
      tree_sitter_fugu_external_scanner_scan,
      tree_sitter_fugu_external_scanner_serialize,
      tree_sitter_fugu_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
